### ISSUE TITLE
Road to Beta

### ISSUE THREAD

**Issue by samselikoff** [tedconf/front_end_builds#44]
Admin

- [x] Fix FontAwesome and other missing assets (#26)
- [x] Single live build - no more "active/inactive" builds
- [x] ~~Make API in admin key copyable (#16)~~
- [x] Fix namespace (#13)
- [x] Fix baseurl (#12)
- [x] Admin lets you make a build live (#10)

Backend
- [x] SSH keys (#41)
- [ ] No more deploy.js? (#47)
- [x] ~~PUT builds (#45)~~
- [x] PUT apps ([PR](https://github.com/tedconf/front_end_builds/pull/53))

**Comment by ryanto** [comment]
I'd like to add some items to this, but would like feedback before they go in the list.

* Get front end tests all buttoned up (making sure we have right coverage + using pretenderify)
* Wizard for adding an app.

**Comment by ryanto** [comment]
I think we can close this since SSH signatures have landed. It still feels pretty alpha to me, but I do think that API is pretty solid now. Thoughts?

**Comment by samselikoff** [comment]
yep absolutely. great work man
